# Paths
path_data: 'https://archive.ics.uci.edu/ml/machine-learning-databases/concrete/compressive/Concrete_Data.xls'

cols_mapping:
    'Cement (component 1)(kg in a m^3 mixture)': 'cement'
    'Blast Furnace Slag (component 2)(kg in a m^3 mixture)': 'slag'
    'Fly Ash (component 3)(kg in a m^3 mixture)': 'ash'
    'Water  (component 4)(kg in a m^3 mixture)': 'water'
    'Superplasticizer (component 5)(kg in a m^3 mixture)': 'superplasticizer'
    'Coarse Aggregate  (component 6)(kg in a m^3 mixture)': 'coarse_aggregate'
    'Fine Aggregate (component 7)(kg in a m^3 mixture)': 'fine_aggregate'
    'Age (day)': 'age'
    'Concrete compressive strength(MPa, megapascals) ': 'strength'

cols_features: 
    - 'cement'
    - 'slag'
    - 'ash'
    - 'water'
    - 'superplasticizer'
    - 'coarse_aggregate'
    - 'fine_aggregate'
    - 'age'
    

cols_composition: 
    - 'cement'
    - 'slag'
    - 'ash'
    - 'water'
    - 'superplasticizer'
    - 'coarse_aggregate'
    - 'fine_aggregate'

cols_solids: 
    - 'cement'
    - 'slag'
    - 'ash'
    - 'superplasticizer'
    - 'coarse_aggregate'
    - 'fine_aggregate'

cols_ratio_aggregates_solids_num: 
    - 'coarse_aggregate'
    - 'fine_aggregate'

cols_ratio_aggregates_solids_den: 
    - 'cement'
    - 'slag'
    - 'ash'
    - 'superplasticizer'

cols_ratio_cement_water_num: 
    - 'cement'

cols_ratio_cement_water_den: 
    - 'water'

cols_target: 'strength'

# Parameters for feature engineering
fe_drop_constant_params:
    tol: 1
    missing_values: 'ignore'

fe_smart_correlation_params:
    threshold: 0.90
    method: 'pearson'
    selection_method: 'missing_values'
    missing_values: 'ignore'

# Parameters for model training, validation and tracking
test_size: 0.2
stratify_by: 'age'
search_iterations: 10

cv_scores: 
    - 'mse'
    - 'rmse'
    - 'mae'
    - 'mape'
    - 'max_error'
    - 'r2'

cv_metric: 'mse'
cv_folds: 10

mlflow_bool: False
mlflow_tracking_uri: 'http://localhost:5000'
mlflow_experiment_name: 'concrete-strength-prediction'

project_name: 'concrete-strength-prediction'

# Other Parameters
bool_verbose: True
seed: 1

n_jobs: -1
n_features: 8
