os:
- linux

language: python

python:
- 3.9
- 3.8

install: pip install -U tox-travis

script:
- tox

before_deploy:
- make dist

deploy:
  provider: pypi
  username: __token__
  password:
    secure: 0M5tsc5VfDzpmNEx1mzW1T70YXLboWRCaNYdTjg7DcyF7\/i6Csd3LfjdUPEbD4Y\+h9LcVqdfuEsmSX5vjN7E6Es\+ugqfBxFik4MW0iNxy09HWZXenrfKwAgujUe0\+1HpRxL53Xjm86tOYYLPL3qL2VXxgGtWZXLj\+Sd\/\/8BH8khdfshXF88D5brX1FhOI94ve\/DTAuHQaZk7CXhN5M5LKumedsMCGRdXMI073E4sr42k7MXa\+wwDfTc8gYs1pZm3TVMQbki5st9CsYiAEGziAUS3SdBjDkHXCsg4SSyIw7L\/yK\+zCUmsz48FegYh0uqOebj\/OMPHCInKPAYHkxO1\+72XkqIn4VuH2gvJi3b4vGYk8jGWyzxz3CvTt\+DcNdvvVEwtQqc8jxeJBwshVv5mhrqlLxBVAVNOaLvIS1g\+wsKoWA994t\/VYhgn9g8ti3\+lhC\+zBrLGpz7x5ll5Lg1\+Ny4yY6WSKcLUOWEWsu6cpJgTnMDGwpt4WLvUjSyMRzpdqEQZPMi9fISeTPj\+RFyui01nPL\+jar08vs\/HjyyWTmeRCtVvfe\+PIZqY4IO3X\+F9ne9I1XIgm8PPgGOP4P1agSwJ\+6oKLuwVmPei3M5ruA7vZP8lhMI56Nl6CjPWGs\+n95rJIDHec92vXs5eXiS43P7AmvPk1wzZL1O5rMTe3fM\=
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true

after_deploy: echo 'Deployment Completed'
